[[Image:NM_cover.jpg|thumb|left|150px|Cover of the July 2012 issue of Nature Methods with a mosaic by Pavel Tomancak]]

Nature Methods July issue [http://www.nature.com/nmeth/focus/bioimageinformatics/index.html focuses] on Bioimage Informatics and there are several papers dealing with or using Fiji.

Most importantly, a [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2019.html perspective] authored by all Fiji core developers headed by Johannes Schindelin, serves as a manifesto of the Fiji project and provides a primary reference to cite Fiji in scientific publications.

Albert Cardona and Pavel Tomancak [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2082.html discuss] the challenges facing open source movements in academia, using Fiji and the hackathons as positive examples of the impact open source communities have on science.

A large [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2084.html review], authored by representatives of all major projects in the bioimage analysis area, discusses the tremendous diversity of options biologists have at their fingertips to deal with image data with special emphasis on open source tools.

The focus contains perspectives on two other open source platforms for bioimage analysis, [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2075.html Icy] and [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2047.html BioImageXD] (both of which attended our [[2011-12-14_-_Fiji_Hackathon_in_Dresden|latest hackathon]]) as well as an excellent [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2073.html commentary] on interoperability which remains the challenge for the community.

The history of ImageJ is [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2089.html discussed] by who else but {{Person|Rasband}} and Kevin Eliceiri. Gene Myers [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2024.html explains] how the bioimage informatics field resembles early days in bioinformatics which is indeed confirmation for everyone involved that we are doing the right thing.

Finally, there is a great diversity of scientific papers describing image analysis tools including Stephan Saalfeld's spectacular EM registration [http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2072.html paper].

The cover of the issue features a mosaic generated by a brand new Fiji plugin written by Pavel Tomancak called poignantly [[CoverMaker_plugin|Cover Maker]].

Big congratulation to the entire Fiji, ImageJ and bioimage analysis community as this is the pinnacle of their hard work. 

The papers will be open access for three months so hurry up, download, read and please cite ;-).

[[Category:News]]
