<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = registration 3d
| url = https://imagej.net/registration_3d
| source = {{GitHub | org=fiji | repo=registration_3d | tag=registration_3d-2.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=registration_3d | v=2.0.1 | label=2.0.1}}
| date = Tue May 02 10:35:27 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|StephanPreibisch}}, {{Person|acardona}}
| leads = {{Person|StephanPreibisch}}
| debuggers = {{Person|StephanPreibisch}}
| reviewers = {{Person|StephanPreibisch}}
| support = {{Person|StephanPreibisch}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|acardona}}, {{Person|dscho}}, {{Person|hinerm}}
}}
