<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = FS Align TrakEM2
| url = https://imagej.net/FS_Align_TrakEM2
| source = {{GitHub | org=fiji | repo=FS_Align_TrakEM2 | tag=FS_Align_TrakEM2-2.0.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=FS_Align_TrakEM2 | v=2.0.2 | label=2.0.2}}
| date = Tue May 02 10:18:27 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=yes | support=yes}}
| founders = {{Person|larrylindsey}}
| leads = {{Person|larrylindsey}}
| reviewers = {{Person|larrylindsey}}
| support = {{Person|larrylindsey}}
| maintainers = {{Person|larrylindsey}}, {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}, {{Person|axtimwalde}}
}}
