<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = SciJava
| name = SciJava Scripting: Groovy
| url = https://github.com/scijava/scripting-groovy
| source = {{GitHub | org=scijava | repo=scripting-groovy | tag=scripting-groovy-0.2.6}}
| license = [[BSD-2]]
| release = {{Maven | g=org.scijava | a=scripting-groovy | v=0.2.6 | label=0.2.6}}
| date = Sun Apr 30 14:12:03 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|ctrueden}}
| leads = {{Person|ctrueden}}
| developers = {{Person|ctrueden}}
| debuggers = {{Person|ctrueden}}
| reviewers = {{Person|ctrueden}}
| support = {{Person|ctrueden}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|hinerm}}, Sundararajan Athijegannathan, Mike Grogan
}}
