<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Sync Win
| url = https://imagej.net/Sync_Win
| source = {{GitHub | org=fiji | repo=Sync_Win | tag=Sync_Win-1.7-fiji4}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=Sync_Win | v=1.7-fiji4 | label=1.7-fiji4}}
| date = Sat Apr 29 23:09:46 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = Patrick Kelly
| maintainers = {{Person|ctrueden}}
| contributors = Patrick Kelly, {{Person|dscho}}, {{Person|hinerm}}, Joachim Walter
}}
