<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = VIB-lib
| url = https://imagej.net/VIB-lib
| source = {{GitHub | org=fiji | repo=VIB-lib | tag=VIB-lib-2.1.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=VIB-lib | v=2.1.2 | label=2.1.2}}
| date = Tue May 02 10:39:08 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|dscho}}, {{Person|bene51}}, {{Person|mhl}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|bene51}}, {{Person|mhl}}, {{Person|iarganda}}, {{Person|acardona}}, {{Person|imagejan}}, {{Person|hinerm}}, [[User:Hornung|Daniel Hornung]], {{Person|StephanPreibisch}}, {{Person|axtimwalde}}, Paul Chew, Francois Kusztos, Glen Smith
}}
