<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = VectorString
| url = https://imagej.net/TrakEM2
| source = {{GitHub | org=trakem2 | repo=TrakEM2 | tag=VectorString-2.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=VectorString | v=2.0.1 | label=2.0.1}}
| date = Tue May 02 16:09:32 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=yes | support=yes}}
| founders = {{Person|acardona}}
| leads = {{Person|acardona}}, {{Person|axtimwalde}}
| reviewers = {{Person|axtimwalde}}
| support = {{Person|acardona}}
| maintainers = {{Person|axtimwalde}}, {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}
}}
