<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = BigDataViewer Fiji
| url = https://imagej.net/BigDataViewer
| source = {{GitHub | org=bigdataviewer | repo=bigdataviewer_fiji | tag=bigdataviewer_fiji-3.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=bigdataviewer_fiji | v=3.0.1 | label=3.0.1}}
| date = Wed May 24 15:48:27 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|tpietzsch}}
| leads = {{Person|tpietzsch}}
| developers = {{Person|tpietzsch}}
| debuggers = {{Person|tpietzsch}}
| reviewers = {{Person|tpietzsch}}
| support = {{Person|tpietzsch}}
| maintainers = {{Person|tpietzsch}}, {{Person|ctrueden}}
| contributors = {{Person|StephanPreibisch}}, {{Person|hkmoon}}
}}
