<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = ImageJ
| name = SciJava Script Editor
| url = https://github.com/scijava/script-editor
| source = {{GitHub | org=scijava | repo=script-editor | tag=script-editor-0.1.4}}
| license = [[BSD-2]]
| release = {{Maven | g=org.scijava | a=script-editor | v=0.1.4 | label=0.1.4}}
| date = Mon May 15 15:39:38 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|ctrueden}}, {{Person|dscho}}, Sumit Dubey
| leads = {{Person|ctrueden}}
| developers = {{Person|ctrueden}}
| debuggers = {{Person|ctrueden}}
| reviewers = {{Person|ctrueden}}
| support = {{Person|ctrueden}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, Sumit Dubey, {{Person|acardona}}, {{Person|imagejan}}, {{Person|skalarproduktraum}}, {{Person|Squareys}}, {{Person|stelfrich}}, {{Person|hinerm}}, {{Person|sinverso}}, {{Person|tomka}}, Jacques Pecreaux, {{Person|stuyvenberg}}, {{Person|tinevez}}, {{Person|panovr}}
}}
