<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = ImgLib2
| name = ImgLib2 Scripting
| url = https://github.com/imglib/imglib2-script
| source = {{GitHub | org=imglib | repo=imglib2-script | tag=imglib2-script-0.2.2}}
| license = [[GPLv2]]
| release = {{Maven | g=net.imglib2 | a=imglib2-script | v=0.2.2 | label=0.2.2}}
| date = Tue May 02 16:40:18 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| contributors = TODO
}}
