<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = SciJava
| name = SciJava Grab
| url = https://github.com/scijava/scijava-grab
| source = {{GitHub | org=scijava | repo=scijava-grab | tag=scijava-grab-0.1.0}}
| license = [[BSD-2]]
| release = {{Maven | g=org.scijava | a=scijava-grab | v=0.1.0 | label=0.1.0}}
| date = Wed May 24 13:34:20 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|ctrueden}}, {{Person|hadim}}
| leads = {{Person|ctrueden}}
| developers = {{Person|ctrueden}}
| debuggers = {{Person|ctrueden}}
| reviewers = {{Person|ctrueden}}
| support = {{Person|ctrueden}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|hadim}}
}}
