<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = fiji-compat
| url = https://github.com/fiji/fiji-compat
| source = {{GitHub | org=fiji | repo=fiji-compat | tag=fiji-compat-2.0.3}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=fiji-compat | v=2.0.3 | label=2.0.3}}
| date = Tue May 16 15:55:38 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|dscho}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}, {{Person|mhl}}
}}
