<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Stack Manipulation
| url = https://imagej.net/Stack_Manipulation
| source = {{GitHub | org=fiji | repo=Stack_Manipulation | tag=Stack_Manipulation-2.0.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=Stack_Manipulation | v=2.0.2 | label=2.0.2}}
| date = Sat Apr 29 23:08:20 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|tinevez}}, Tony Collins, Patrick Kelly, J. Anthony Parker, {{Person|rasband}}
| debuggers = {{Person|tinevez}}
| reviewers = {{Person|tinevez}}
| support = {{Person|tinevez}}
| maintainers = {{Person|tinevez}}, {{Person|ctrueden}}
| contributors = Tony Collins, Patrick Kelly, J. Anthony Parker, {{Person|rasband}}, {{Person|dscho}}, {{Person|hinerm}}
}}
