<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Manual Tracking
| url = https://imagej.net/Manual_Tracking
| source = {{GitHub | org=fiji | repo=Manual_Tracking | tag=Manual_Tracking-2.1.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=Manual_Tracking | v=2.1.1 | label=2.1.1}}
| date = Sat Apr 29 22:57:32 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|fab2506}}, {{Person|dscho}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|fab2506}}, {{Person|dscho}}, {{Person|hinerm}}, {{Person|tomka}}
}}
