<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Volume Calculator
| url = https://imagej.net/Volume_Calculator
| source = {{GitHub | org=fiji | repo=Volume_Calculator | tag=Volume_Calculator-2.0.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=Volume_Calculator | v=2.0.2 | label=2.0.2}}
| date = Sat Apr 29 23:18:59 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|pcmarks}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|pcmarks}}, {{Person|dscho}}, {{Person|imagejan}}, {{Person|hinerm}}
}}
