<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Vaa3d Writer
| url = https://imagej.net/Vaa3d_Writer
| source = {{GitHub | org=berl | repo=Vaa3d_Writer | tag=Vaa3d_Writer-1.0.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=Vaa3d_Writer | v=1.0.2 | label=1.0.2}}
| date = Sat Apr 29 23:17:33 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|berl}}
| leads = {{Person|berl}}
| debuggers = {{Person|berl}}
| reviewers = {{Person|berl}}
| support = {{Person|berl}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}
}}
