<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = ToAST
| url = https://imagej.net/ToAST
| source = {{GitHub | org=fiji | repo=ToAST | tag=ToAST_-25.0.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=ToAST_ | v=25.0.2 | label=25.0.2}}
| date = Sat Apr 29 23:12:04 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = Misha Kudryashev
| contributors = [[User:Kudryashev|Misha Kudryashev]], {{Person|dscho}}, {{Person|hinerm}}
}}
