<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Statistical Region Merging
| url = https://imagej.net/Statistical_Region_Merging
| source = {{GitHub | org=fiji | repo=Statistical_Region_Merging | tag=Statistical_Region_Merging-2.0.1}}
| license = [[BSD-2]]
| release = {{Maven | g=sc.fiji | a=Statistical_Region_Merging | v=2.0.1 | label=2.0.1}}
| date = Sat Apr 29 23:09:03 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|dscho}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}
}}
