<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Kuwahara Filter
| url = https://imagej.net/Kuwahara_Filter
| source = {{GitHub | org=fiji | repo=Kuwahara_Filter | tag=Kuwahara_Filter-2.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=Kuwahara_Filter | v=2.0.1 | label=2.0.1}}
| date = Sat Apr 29 22:51:34 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=no | support=yes}}
| founders = {{Person|rasband}}, {{Person|dscho}}
| leads = {{Person|rasband}}
| debuggers = {{Person|rasband}}
| support = {{Person|rasband}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}
}}
