<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = VIB
| url = https://imagej.net/VIB
| source = {{GitHub | org=fiji | repo=VIB | tag=VIB_-3.0.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=VIB_ | v=3.0.2 | label=3.0.2}}
| date = Sat Apr 29 23:16:03 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|mhl}}, {{Person|dscho}}, {{Person|bene51}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|mhl}}, {{Person|dscho}}, {{Person|bene51}}, {{Person|rimadoma}}, {{Person|hinerm}}, {{Person|cmci}}, Michel Teussink
}}
