<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = 3D Objects Counter
| url = https://imagej.net/3D_Objects_Counter
| source = {{GitHub | org=fiji | repo=3D_Objects_Counter | tag=3D_Objects_Counter-2.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=3D_Objects_Counter | v=2.0.1 | label=2.0.1}}
| date = Sat Apr 29 22:18:19 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=yes | support=yes}}
| founders = {{Person|fab2506}}
| leads = {{Person|chalkie666}}
| reviewers = {{Person|chalkie666}}
| support = {{Person|chalkie666}}
| maintainers = {{Person|chalkie666}}, {{Person|ctrueden}}
| contributors = {{Person|fab2506}}, {{Person|dscho}}, {{Person|ehrenfeu}}, {{Person|hinerm}}
}}
