<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = SPIM Opener
| url = https://imagej.net/SPIM_Opener
| source = {{GitHub | org=fiji | repo=SPIM_Opener | tag=SPIM_Opener-2.0.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=SPIM_Opener | v=2.0.2 | label=2.0.2}}
| date = Sat Apr 29 23:01:14 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|bene51}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|bene51}}, {{Person|dscho}}, {{Person|hinerm}}, {{Person|tpietzsch}}
}}
