<noinclude>{{Autogenerated|template}}</noinclude>{| class="component-table"
| '''Name'''
| '''Description'''
| '''Repository'''
| '''Artifact'''
| '''[[License]]'''
| '''[[Team]]'''
|-
| [https://github.com/scijava/scijava-common SciJava Common]
| SciJava Common is a shared library for SciJava software. It provides a plugin framework, with an extensible mechanism for service discovery, backed by its own annotation processor, so that plugins can be loaded dynamically. It is used by downstream projects in the SciJava ecosystem, such as ImageJ and SCIFIO.
| {{GitHub | org=scijava | repo=scijava-common}}
| {{Maven | g=org.scijava | a=scijava-common | label=scijava-common}}
| [[BSD-2]]
| {{Person|ctrueden}}
|-
| [https://github.com/scijava/scijava-config SciJava Configuration]
| SciJava Configuration is a shared collection of files for SciJava software. It provides configuration files for common SciJava dependencies, such as logback and slf4j.
| {{GitHub | org=scijava | repo=scijava-config}}
| {{Maven | g=org.scijava | a=scijava-config | label=scijava-config}}
| [[BSD-2]]
| {{Person|ctrueden}}
|-
| Logback Classic Module
| logback-classic module
| 
| {{Maven | g=ch.qos.logback | a=logback-classic | label=logback-classic}}
| [http://www.eclipse.org/legal/epl-v10.html Eclipse Public License - v 1.0], [http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html GNU Lesser General Public License]
| {{Person|ceki}}, {{Person|hixi}}
|-
| [[SCIFIO|SCIFIO-Bio-Formats Compatibility Format]]
| Compatibility layer for using un-converted Bio-Formats readers in SCIFIO applications.
| {{GitHub | org=scifio | repo=scifio-bf-compat}}
| {{Maven | g=io.scif | a=scifio-bf-compat | label=scifio-bf-compat}}
| [[BSD-2]]
| {{Person|ctrueden}}
|-
| [[SCIFIO HDF5|SCIFIO HDF5]]
| SCIFIO plugins for HDF5-based formats.
| {{GitHub | org=scifio | repo=scifio-hdf5}}
| {{Maven | g=io.scif | a=scifio-hdf5 | label=scifio-hdf5}}
| [[BSD-2]]
| {{Person|henrypinkard}}, {{Person|ctrueden}}
|-
| [[SCIFIO Life Sciences Extension|SCIFIO Life Sciences Extension]]
| Provides SCIFIO support for proprietary life science formats.
| {{GitHub | org=scifio | repo=scifio-lifesci}}
| {{Maven | g=io.scif | a=scifio-lifesci | label=scifio-lifesci}}
| [[GPLv2]]
| {{Person|ctrueden}}
|-
| [[SCIFIO-OME-XML|SCIFIO OME-XML Extension]]
| SCIFIO support for the OME data model, including OME-XML and OME-TIFF.
| {{GitHub | org=scifio | repo=scifio-ome-xml}}
| {{Maven | g=io.scif | a=scifio-ome-xml | label=scifio-ome-xml}}
| [[BSD-2]]
| {{Person|ctrueden}}
|-
| [[Welcome|ImageJ]]
| ImageJ is an open source Java image processing program inspired by NIH Image for the Macintosh.
| {{GitHub | org=imagej | repo=imagej}}
| {{Maven | g=net.imagej | a=imagej | label=imagej}}
| [[BSD-2]]
| {{Person|ctrueden}}
|-
| [[ImageJ Legacy|ImageJ Legacy Bridge]]
| The legacy component enables backward compatibility with the legacy version of ImageJ (1.x). It contains the code necessary to translate ImageJ images into ImageJ1 format and back, so that legacy plugins can be executed faithfully.
| {{GitHub | org=imagej | repo=imagej-legacy}}
| {{Maven | g=net.imagej | a=imagej-legacy | label=imagej-legacy}}
| [[BSD-2]]
| {{Person|ctrueden}}
|-
| [[Op Finder|Op Finder]]
| Interactive UI component for browsing and running available Ops.
| {{GitHub | org=imagej | repo=op-finder}}
| {{Maven | g=net.imagej | a=op-finder | label=op-finder}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/3D_Blob_Segmentation 3D Blob Segmentation]
| 3D Blob Segmentation plugin for Fiji.
| {{GitHub | org=fiji | repo=3D_Blob_Segmentation}}
| {{Maven | g=sc.fiji | a=3D_Blob_Segmentation | label=3D_Blob_Segmentation}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/3D_Objects_Counter 3D Objects Counter]
| 3D Objects Counter plugin for Fiji.
| {{GitHub | org=fiji | repo=3D_Objects_Counter}}
| {{Maven | g=sc.fiji | a=3D_Objects_Counter | label=3D_Objects_Counter}}
| [[GPLv3]]
| {{Person|chalkie666}}, {{Person|ctrueden}}
|-
| [https://imagej.net/3D_Viewer 3D Viewer]
| 3D Viewer for visualizing image stacks three-dimensionally.
| {{GitHub | org=fiji | repo=3D_Viewer}}
| {{Maven | g=sc.fiji | a=3D_Viewer | label=3D_Viewer}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [[AnalyzeSkeleton|Analyze Skeleton]]
| Analysis of 2D and 3D skeleton images.
| {{GitHub | org=fiji | repo=AnalyzeSkeleton}}
| {{Maven | g=sc.fiji | a=AnalyzeSkeleton_ | label=AnalyzeSkeleton_}}
| [[GPLv3]]
| {{Person|iarganda}}, {{Person|ctrueden}}
|-
| [[Anisotropic Diffusion 2D|Anisotropic Diffusion 2D]]
| Anisotropic Diffusion 2D plugin for Fiji.
| {{GitHub | org=fiji | repo=Anisotropic_Diffusion_2D}}
| {{Maven | g=sc.fiji | a=Anisotropic_Diffusion_2D | label=Anisotropic_Diffusion_2D}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Archipelago_Plugins Archipelago Plugins]
| Archipelago Plugins plugin for Fiji.
| {{GitHub | org=fiji | repo=Archipelago_Plugins}}
| {{Maven | g=sc.fiji | a=Archipelago_Plugins | label=Archipelago_Plugins}}
| [[GPLv3]]
| {{Person|larrylindsey}}, {{Person|ctrueden}}
|-
| [[Arrow|Arrow]]
| Arrow plugin for Fiji.
| {{GitHub | org=fiji | repo=Arrow}}
| {{Maven | g=sc.fiji | a=Arrow_ | label=Arrow_}}
| [[GPLv3]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| [[Auto Threshold|Auto Threshold]]
| Auto Threshold plugin for Fiji.
| {{GitHub | org=fiji | repo=Auto_Threshold}}
| {{Maven | g=sc.fiji | a=Auto_Threshold | label=Auto_Threshold}}
| [[GPLv3]]
| {{Person|landinig}}, {{Person|ctrueden}}
|-
| [[Balloon|Balloon Segmentation]]
| Balloon Segmentation plugin for Fiji.
| {{GitHub | org=fiji | repo=BalloonSegmentation}}
| {{Maven | g=sc.fiji | a=BalloonSegmentation_ | label=BalloonSegmentation_}}
| [[GPLv2]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Bug_Submitter Bug Submitter]
| Bug Submitter plugin for Fiji.
| {{GitHub | org=fiji | repo=Bug_Submitter}}
| {{Maven | g=sc.fiji | a=Bug_Submitter | label=Bug_Submitter}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/CPU_Meter CPU Meter]
| CPU Meter plugin for Fiji.
| {{GitHub | org=fiji | repo=CPU_Meter}}
| {{Maven | g=sc.fiji | a=CPU_Meter | label=CPU_Meter}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [[Calculator Plus|Calculator Plus]]
| Calculator Plus plugin for Fiji.
| {{GitHub | org=fiji | repo=Calculator_Plus}}
| {{Maven | g=sc.fiji | a=Calculator_Plus | label=Calculator_Plus}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [[Cell Counter|Cell Counter]]
| Cell Counter plugin for ImageJ.
| {{GitHub | org=fiji | repo=Cell_Counter}}
| {{Maven | g=sc.fiji | a=Cell_Counter | label=Cell_Counter}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Coloc_2 Coloc 2]
| Fiji's plugin for colocalization analysis.
| {{GitHub | org=fiji | repo=Colocalisation_Analysis}}
| {{Maven | g=sc.fiji | a=Colocalisation_Analysis | label=Colocalisation_Analysis}}
| [[GPLv3]]
| {{Person|chalkie666}}, {{Person|tomka}}, {{Person|etarena}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Color_Histogram Color Histogram]
| Color Histogram plugin for Fiji.
| {{GitHub | org=fiji | repo=Color_Histogram}}
| {{Maven | g=sc.fiji | a=Color_Histogram | label=Color_Histogram}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [[Color Inspector 3D|Color Inspector 3D]]
| Color Inspector 3D plugin for Fiji.
| {{GitHub | org=fiji | repo=Color_Inspector_3D}}
| {{Maven | g=sc.fiji | a=Color_Inspector_3D | label=Color_Inspector_3D}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Colour_Deconvolution Colour Deconvolution]
| Colour Deconvolution plugin for Fiji.
| {{GitHub | org=fiji | repo=Colour_Deconvolution}}
| {{Maven | g=sc.fiji | a=Colour_Deconvolution | label=Colour_Deconvolution}}
| [[GPLv3]]
| {{Person|landinig}}, {{Person|ctrueden}}
|-
| [[Bleach Correction|CorrectBleach]]
| CorrectBleach plugin for Fiji.
| {{GitHub | org=fiji | repo=CorrectBleach}}
| {{Maven | g=sc.fiji | a=CorrectBleach_ | label=CorrectBleach_}}
| [[GPLv3]]
| {{Person|cmci}}, {{Person|ctrueden}}
|-
| [[Correct 3D Drift|Correct 3D Drift]]
| Script to register time frames (stacks) to each other.
| {{GitHub | org=fiji | repo=Correct_3D_Drift}}
| {{Maven | g=sc.fiji | a=Correct_3D_Drift | label=Correct_3D_Drift}}
| [[GPLv3]]
| {{Person|tischi}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Descriptor_based_registration Descriptor based registration]
| Descriptor based registration plugin for Fiji.
| {{GitHub | org=fiji | repo=Descriptor_based_registration}}
| {{Maven | g=sc.fiji | a=Descriptor_based_registration | label=Descriptor_based_registration}}
| [[GPLv3]]
| {{Person|StephanPreibisch}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Dichromacy Dichromacy]
| Dichromacy plugin for Fiji.
| {{GitHub | org=fiji | repo=Dichromacy}}
| {{Maven | g=sc.fiji | a=Dichromacy_ | label=Dichromacy_}}
| [[GPLv3]]
| {{Person|landinig}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Directionality Directionality]
| Directionality plugin for Fiji.
| {{GitHub | org=fiji | repo=Directionality}}
| {{Maven | g=sc.fiji | a=Directionality_ | label=Directionality_}}
| [[GPLv3]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| [https://imagej.net/FS_Align_TrakEM2 FS Align TrakEM2]
| FS Align TrakEM2 plugin for Fiji.
| {{GitHub | org=fiji | repo=FS_Align_TrakEM2}}
| {{Maven | g=sc.fiji | a=FS_Align_TrakEM2 | label=FS_Align_TrakEM2}}
| [[GPLv3]]
| {{Person|larrylindsey}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Feature_Detection Feature Detection]
| Feature Detection plugin for Fiji.
| {{GitHub | org=fiji | repo=Feature_Detection}}
| {{Maven | g=sc.fiji | a=Feature_Detection | label=Feature_Detection}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Fiji_Archipelago Fiji Archipelago]
| Fiji Archipelago plugin for Fiji.
| {{GitHub | org=fiji | repo=Fiji_Archipelago}}
| {{Maven | g=sc.fiji | a=Fiji_Archipelago | label=Fiji_Archipelago}}
| [[GPLv2]]
| {{Person|larrylindsey}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Fiji_Developer Fiji Developer]
| Fiji Developer plugin for Fiji.
| {{GitHub | org=fiji | repo=Fiji_Developer}}
| {{Maven | g=sc.fiji | a=Fiji_Developer | label=Fiji_Developer}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Fiji_Package_Maker Fiji Package Maker]
| Fiji Package Maker plugin for Fiji.
| {{GitHub | org=fiji | repo=Fiji_Package_Maker}}
| {{Maven | g=sc.fiji | a=Fiji_Package_Maker | label=Fiji_Package_Maker}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Fiji_Plugins Fiji Plugins]
| Fiji Plugins plugin for Fiji.
| {{GitHub | org=fiji | repo=Fiji_Plugins}}
| {{Maven | g=sc.fiji | a=Fiji_Plugins | label=Fiji_Plugins}}
| [[GPLv2]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/FlowJ FlowJ]
| FlowJ plugin for Fiji.
| {{GitHub | org=fiji | repo=FlowJ}}
| {{Maven | g=sc.fiji | a=FlowJ_ | label=FlowJ_}}
| [[GPLv3]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Graph_Cut Graph Cut]
| Graph Cut plugin for Fiji.
| {{GitHub | org=fiji | repo=Graph_Cut}}
| {{Maven | g=sc.fiji | a=Graph_Cut | label=Graph_Cut}}
| [[GPLv3]]
| {{Person|funkey}}, {{Person|ctrueden}}
|-
| [[Gray Morphology|Gray Morphology]]
| Gray Morphology plugin for Fiji.
| {{GitHub | org=fiji | repo=Gray_Morphology}}
| {{Maven | g=sc.fiji | a=Gray_Morphology | label=Gray_Morphology}}
| [[GPLv3]]
| {{Person|dprodanov}}, {{Person|ctrueden}}
|-
| [[Helmholtz Analysis|Helmholtz Analysis]]
| Helmholtz Analysis plugin for Fiji.
| {{GitHub | org=fiji | repo=Helmholtz_Analysis}}
| {{Maven | g=sc.fiji | a=Helmholtz_Analysis | label=Helmholtz_Analysis}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [[IJ Robot|IJ Robot]]
| IJ Robot plugin for Fiji.
| {{GitHub | org=fiji | repo=IJ_Robot}}
| {{Maven | g=sc.fiji | a=IJ_Robot | label=IJ_Robot}}
| [[GPLv3]]
| {{Person|landinig}}, {{Person|ctrueden}}
|-
| [https://imagej.net/IO IO]
| IO plugin for Fiji.
| {{GitHub | org=fiji | repo=IO}}
| {{Maven | g=sc.fiji | a=IO_ | label=IO_}}
| [[GPLv3]]
| {{Person|jefferis}}, {{Person|ctrueden}}
|-
| [[Image 5D|Image5D]]
| The Image5D plugins extend image stacks to 5 dimensions: x, y, channel (color), slice (z), frame (t).
| {{GitHub | org=fiji | repo=Image_5D}}
| {{Maven | g=sc.fiji | a=Image_5D | label=Image_5D}}
| [[BSD-2]]
| {{Person|ctrueden}}
|-
| [[Image Expression Parser|Image Expression Parser]]
| Image Expression Parser plugin for Fiji.
| {{GitHub | org=fiji | repo=Image_Expression_Parser}}
| {{Maven | g=sc.fiji | a=Image_Expression_Parser | label=Image_Expression_Parser}}
| [[GPLv3]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| plugins/Interactive_3D_Surface_Plot.jar
| 
| {{GitHub | org=fiji | repo=Interactive_3D_Surface_Plot}}
| {{Maven | g=sc.fiji | a=Interactive_3D_Surface_Plot | label=Interactive_3D_Surface_Plot}}
| [[GPLv3]]
| {{Person|dscho}}, {{Person|ctrueden}}, {{Person|hinerm}}
|-
| [https://imagej.net/IsoData_Classifier IsoData Classifier]
| IsoData Classifier plugin for Fiji.
| {{GitHub | org=fiji | repo=IsoData_Classifier}}
| {{Maven | g=sc.fiji | a=IsoData_Classifier | label=IsoData_Classifier}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Kuwahara_Filter Kuwahara Filter]
| Kuwahara Filter plugin for Fiji.
| {{GitHub | org=fiji | repo=Kuwahara_Filter}}
| {{Maven | g=sc.fiji | a=Kuwahara_Filter | label=Kuwahara_Filter}}
| [[GPLv3]]
| {{Person|rasband}}, {{Person|ctrueden}}
|-
| [[LSM Toolbox|LSM Reader]]
| LSM Reader plugin for Fiji.
| {{GitHub | org=fiji | repo=LSM_Reader}}
| {{Maven | g=sc.fiji | a=LSM_Reader | label=LSM_Reader}}
| [[GPLv2]]
| {{Person|ctrueden}}
|-
| [[LSM Toolbox|LSM Toolbox]]
| LSM Toolbox plugin for Fiji.
| {{GitHub | org=fiji | repo=LSM_Toolbox}}
| {{Maven | g=sc.fiji | a=LSM_Toolbox | label=LSM_Toolbox}}
| [[GPLv2]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| [[Lasso and Blow Tool|Lasso and Blow Tool]]
| Lasso and Blow Tool plugin for Fiji.
| {{GitHub | org=fiji | repo=Lasso_and_Blow_Tool}}
| {{Maven | g=sc.fiji | a=Lasso_and_Blow_Tool | label=Lasso_and_Blow_Tool}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Linear_Kuwahara Linear Kuwahara]
| Linear Kuwahara plugin for Fiji.
| {{GitHub | org=fiji | repo=Linear_Kuwahara}}
| {{Maven | g=sc.fiji | a=Linear_Kuwahara | label=Linear_Kuwahara}}
| [[GPLv3]]
| {{Person|tischi}}, {{Person|ctrueden}}
|-
| [[Local Thickness|LocalThickness]]
| Local Thickness is used to compute the local thickness of a 3D image stack.
| {{GitHub | org=fiji | repo=LocalThickness}}
| {{Maven | g=sc.fiji | a=LocalThickness_ | label=LocalThickness_}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [[MTrack2|MTrack2]]
| MTrack2 plugin for Fiji.
| {{GitHub | org=fiji | repo=MTrack2}}
| {{Maven | g=sc.fiji | a=MTrack2_ | label=MTrack2_}}
| [[GPLv3]]
| {{Person|chalkie666}}, {{Person|ctrueden}}
|-
| [https://imagej.net/M_I_P M I P]
| M I P plugin for Fiji.
| {{GitHub | org=fiji | repo=M_I_P}}
| {{Maven | g=sc.fiji | a=M_I_P | label=M_I_P}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Manual_Tracking Manual Tracking]
| Manual Tracking plugin for Fiji.
| {{GitHub | org=fiji | repo=Manual_Tracking}}
| {{Maven | g=sc.fiji | a=Manual_Tracking | label=Manual_Tracking}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [[Multi Kymograph|Multi Kymograph]]
| Measure velocities of moving structures in an image time series.
| {{GitHub | org=fiji | repo=Multi_Kymograph}}
| {{Maven | g=sc.fiji | a=Multi_Kymograph | label=Multi_Kymograph}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/PIV_analyser PIV analyser]
| PIV analyser plugin for Fiji.
| {{GitHub | org=fiji | repo=PIV_analyser}}
| {{Maven | g=sc.fiji | a=PIV_analyser | label=PIV_analyser}}
| [[GPLv3]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| [[QuickPALM|QuickPALM]]
| QuickPALM plugin for Fiji.
| {{GitHub | org=fiji | repo=QuickPALM}}
| {{Maven | g=sc.fiji | a=QuickPALM_ | label=QuickPALM_}}
| [[GPLv3]]
| Ricardo Henriques, {{Person|chalkie666}}, {{Person|ctrueden}}
|-
| [https://imagej.net/RATS RATS]
| RATS plugin for Fiji.
| {{GitHub | org=fiji | repo=RATS}}
| {{Maven | g=sc.fiji | a=RATS_ | label=RATS_}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Reconstruct_Reader Reconstruct Reader]
| Reconstruct Reader plugin for Fiji.
| {{GitHub | org=fiji | repo=Reconstruct_Reader}}
| {{Maven | g=sc.fiji | a=Reconstruct_Reader | label=Reconstruct_Reader}}
| [[GPLv3]]
| {{Person|larrylindsey}}, {{Person|ctrueden}}
|-
| [https://imagej.net/SPIM_Opener SPIM Opener]
| SPIM Opener plugin for Fiji.
| {{GitHub | org=fiji | repo=SPIM_Opener}}
| {{Maven | g=sc.fiji | a=SPIM_Opener | label=SPIM_Opener}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/SPIM_Registration SPIM Registration]
| Software for the reconstruction of multi-view microscopic acquisitions like Selective Plane Illumination Microscopy (SPIM) Data.
| {{GitHub | org=fiji | repo=SPIM_Registration}}
| {{Maven | g=sc.fiji | a=SPIM_Registration | label=SPIM_Registration}}
| [[GPLv2]]
| {{Person|StephanPreibisch}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Samples Samples]
| Samples plugin for Fiji.
| {{GitHub | org=fiji | repo=Samples}}
| {{Maven | g=sc.fiji | a=Samples_ | label=Samples_}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Series_Labeler Series Labeler]
| Series Labeler plugin for Fiji.
| {{GitHub | org=fiji | repo=Series_Labeler}}
| {{Maven | g=sc.fiji | a=Series_Labeler | label=Series_Labeler}}
| [[GPLv3]]
| {{Person|chalkie666}}, {{Person|ctrueden}}
|-
| [[Simple Neurite Tracer|Simple Neurite Tracer]]
| The ImageJ framework for semi-automated tracing of neurons and other tube-like structures.
| {{GitHub | org=fiji | repo=Simple_Neurite_Tracer}}
| {{Maven | g=sc.fiji | a=Simple_Neurite_Tracer | label=Simple_Neurite_Tracer}}
| [[GPLv3]]
| {{Person|tferr}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Siox_Segmentation Siox Segmentation]
| Siox Segmentation plugin for Fiji.
| {{GitHub | org=fiji | repo=Siox_Segmentation}}
| {{Maven | g=sc.fiji | a=Siox_Segmentation | label=Siox_Segmentation}}
| [https://www.apache.org/licenses/LICENSE-2.0.txt Apache Software License, Version 2.0]
| {{Person|iarganda}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Skeletonize3D Skeletonize3D]
| Skeletonize3D plugin for Fiji.
| {{GitHub | org=fiji | repo=Skeletonize3D}}
| {{Maven | g=sc.fiji | a=Skeletonize3D_ | label=Skeletonize3D_}}
| [[GPLv3]]
| {{Person|iarganda}}, {{Person|ctrueden}}
|-
| [https://imagej.net/SplineDeformationGenerator SplineDeformationGenerator]
| SplineDeformationGenerator plugin for Fiji.
| {{GitHub | org=fiji | repo=SplineDeformationGenerator}}
| {{Maven | g=sc.fiji | a=SplineDeformationGenerator_ | label=SplineDeformationGenerator_}}
| [[GPLv3]]
| {{Person|iarganda}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Stack_Manipulation Stack Manipulation]
| Stack Manipulation plugin for Fiji.
| {{GitHub | org=fiji | repo=Stack_Manipulation}}
| {{Maven | g=sc.fiji | a=Stack_Manipulation | label=Stack_Manipulation}}
| [[GPLv3]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Statistical_Region_Merging Statistical Region Merging]
| Statistical Region Merging plugin for Fiji.
| {{GitHub | org=fiji | repo=Statistical_Region_Merging}}
| {{Maven | g=sc.fiji | a=Statistical_Region_Merging | label=Statistical_Region_Merging}}
| [[BSD-2]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Stitching Stitching]
| A plugin for reconstructing big images/stacks from an arbitrary number of tiled input images/stacks.
| {{GitHub | org=fiji | repo=Stitching}}
| {{Maven | g=sc.fiji | a=Stitching_ | label=Stitching_}}
| [[GPLv2]]
| {{Person|StephanPreibisch}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Sync_Win Sync Win]
| Sync Win plugin for Fiji.
| {{GitHub | org=fiji | repo=Sync_Win}}
| {{Maven | g=sc.fiji | a=Sync_Win | label=Sync_Win}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Thread_Killer Thread Killer]
| Thread Killer plugin for Fiji.
| {{GitHub | org=fiji | repo=Thread_Killer}}
| {{Maven | g=sc.fiji | a=Thread_Killer | label=Thread_Killer}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Time_Lapse Time Lapse]
| Time Lapse tools written in conjunction with the work for "A Doppler effect in embryonic pattern formation", Soroldoni et al, Science 11 July 2014: Vol. 345 no. 6193 pp. 222-225, DOI: 10.1126/science.1253089
| {{GitHub | org=fiji | repo=Time_Lapse}}
| {{Maven | g=sc.fiji | a=Time_Lapse | label=Time_Lapse}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Time_Stamper Time Stamper]
| Time Stamper plugin for Fiji.
| {{GitHub | org=fiji | repo=Time_Stamper}}
| {{Maven | g=sc.fiji | a=Time_Stamper | label=Time_Stamper}}
| [[GPLv3]]
| {{Person|chalkie666}}, {{Person|ctrueden}}
|-
| [https://imagej.net/ToAST ToAST]
| ToAST plugin for Fiji.
| {{GitHub | org=fiji | repo=ToAST}}
| {{Maven | g=sc.fiji | a=ToAST_ | label=ToAST_}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/TopoJ TopoJ]
| TopoJ plugin for Fiji.
| {{GitHub | org=fiji | repo=TopoJ}}
| {{Maven | g=sc.fiji | a=TopoJ_ | label=TopoJ_}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/TrackMate TrackMate]
| TrackMate plugin for Fiji.
| {{GitHub | org=fiji | repo=TrackMate}}
| {{Maven | g=sc.fiji | a=TrackMate_ | label=TrackMate_}}
| [[GPLv3]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| [https://imagej.net/TrakEM2_Archipelago TrakEM2 Archipelago]
| TrakEM2 Support for Fiji Archipelago
| {{GitHub | org=fiji | repo=TrakEM2_Archipelago}}
| {{Maven | g=sc.fiji | a=TrakEM2_Archipelago | label=TrakEM2_Archipelago}}
| [[GPLv2]]
| {{Person|larrylindsey}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Trainable_Segmentation Trainable Segmentation]
| Trainable Segmentation plugin for Fiji.
| {{GitHub | org=fiji | repo=Trainable_Segmentation}}
| {{Maven | g=sc.fiji | a=Trainable_Segmentation | label=Trainable_Segmentation}}
| [[GPLv3]]
| {{Person|iarganda}}, {{Person|ctrueden}}
|-
| [https://imagej.net/VIB-lib VIB-lib]
| Support library for all the VIB stuff.
| {{GitHub | org=fiji | repo=VIB-lib}}
| {{Maven | g=sc.fiji | a=VIB-lib | label=VIB-lib}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/VIB VIB]
| VIB plugin for Fiji.
| {{GitHub | org=fiji | repo=VIB}}
| {{Maven | g=sc.fiji | a=VIB_ | label=VIB_}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Vaa3d_Reader Vaa3d Reader]
| Custom reader for Vaa3D application 3D volume file formats .v3draw and .v3dpbd.
| {{GitHub | org=fiji | repo=Vaa3d_Reader}}
| {{Maven | g=sc.fiji | a=Vaa3d_Reader | label=Vaa3d_Reader}}
| [[GPLv3]]
| {{Person|cmbruns}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Vaa3d_Writer Vaa3d Writer]
| Plugin to write .v3draw files readable by Vaa3d.
| {{GitHub | org=berl | repo=Vaa3d_Writer}}
| {{Maven | g=sc.fiji | a=Vaa3d_Writer | label=Vaa3d_Writer}}
| [[GPLv3]]
| {{Person|berl}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Video_Editing Video Editing]
| Video Editing plugin for Fiji.
| {{GitHub | org=fiji | repo=Video_Editing}}
| {{Maven | g=sc.fiji | a=Video_Editing | label=Video_Editing}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/View5D View5D]
| View5D plugin for Fiji.
| {{GitHub | org=fiji | repo=View5D}}
| {{Maven | g=sc.fiji | a=View5D_ | label=View5D_}}
| [[GPLv2]]
| {{Person|tinevez}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Volume_Calculator Volume Calculator]
| The Volume Calculator plugin is designed to let users measure the volumes of arbitrary segments of blood vessels by selecting them directly from a 3D image. Although Volume Calculator was developed for quantification in a mouse hindlimb ischemia experiment, it should be useful for the volume measurement of any network. This possibility is determined by the following requirement: the plugin is configured to work best with images that can be read and analyzed by the Skeleton 3D and Analyze 3D plugins. Hence, it is suggested that users first check their images with these two plugins.
| {{GitHub | org=fiji | repo=Volume_Calculator}}
| {{Maven | g=sc.fiji | a=Volume_Calculator | label=Volume_Calculator}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://imagej.net/Volume_Viewer Volume Viewer]
| Volume Viewer plugin for Fiji.
| {{GitHub | org=fiji | repo=Volume_Viewer}}
| {{Maven | g=sc.fiji | a=Volume_Viewer | label=Volume_Viewer}}
| [[GPLv3]]
| {{Person|kaibarthel}}, {{Person|ctrueden}}
|-
| [https://imagej.net/BUnwarpJ bUnwarpJ]
| bUnwarpJ plugin for Fiji.
| {{GitHub | org=fiji | repo=bUnwarpJ}}
| {{Maven | g=sc.fiji | a=bUnwarpJ_ | label=bUnwarpJ_}}
| [[GPLv3]]
| {{Person|iarganda}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Block_Matching Block Matching]
| Block Matching plugin for Fiji.
| {{GitHub | org=fiji | repo=blockmatching}}
| {{Maven | g=sc.fiji | a=blockmatching_ | label=blockmatching_}}
| [[GPLv3]]
| {{Person|axtimwalde}}, {{Person|ctrueden}}
|-
| [https://github.com/fiji/fiji-compat fiji-compat]
| Old compatibility layer for Fiji.
| {{GitHub | org=fiji | repo=fiji-compat}}
| {{Maven | g=sc.fiji | a=fiji-compat | label=fiji-compat}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [[Fiji-lib|jars/fiji-lib.jar]]
| Utility classes for Fiji-based projects.
| {{GitHub | org=fiji | repo=fiji-lib}}
| {{Maven | g=sc.fiji | a=fiji-lib | label=fiji-lib}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| plugins/H5J_Loader_Plugin.jar
| A Maven project implementing an ImageJ plugin
| {{GitHub | org=fiji | repo=H5J_Loader_Plugin}}
| {{Maven | g=org.janelia | a=H5J_Loader_Plugin | label=H5J_Loader_Plugin}}
| [http://license.janelia.org/license/jfrc_copyright_1_1.html Janelia Farm Research Campus Software Copyright 1.1]
| {{Person|lesfoster}}
|-
| [https://imagej.net/ImgLib1_(deprecated) Legacy ImgLib1]
| This project serves purely for phasing out ImgLib1 in favor of ImgLib2.
| {{GitHub | org=fiji | repo=legacy-imglib1}}
| {{Maven | g=sc.fiji | a=legacy-imglib1 | label=legacy-imglib1}}
| [[BSD-2]], [[GPLv2]]
| {{Person|StephanPreibisch}}, {{Person|axtimwalde}}, {{Person|ctrueden}}
|-
| [https://imagej.net/Level_Sets Level Sets]
| Level Sets plugin for Fiji.
| {{GitHub | org=fiji | repo=level_sets}}
| {{Maven | g=sc.fiji | a=level_sets | label=level_sets}}
| [[GPLv3]]
| {{Person|ctrueden}}
|-
| [https://github.com/fiji/pal-optimization pal-optimization]
| PAL: Phylogenetic Analysis Library
| {{GitHub | org=fiji | repo=pal-optimization}}
| {{Maven | g=sc.fiji | a=pal-optimization | label=pal-optimization}}
| [http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License v3+]
| {{Person|ctrueden}}
|-
| [https://imagej.net/panorama panorama]
| panorama plugin for Fiji.
| {{GitHub | org=fiji | repo=panorama}}
| {{Maven | g=sc.fiji | a=panorama_ | label=panorama_}}
| [[GPLv3]]
| {{Person|axtimwalde}}, {{Person|ctrueden}}
|-
| [[Register Virtual Stack Slices|Register Virtual Stack Slices]]
| Registers image slices from a sequence of image slices stored in a folder.
| {{GitHub | org=fiji | repo=register_virtual_stack_slices}}
| {{Maven | g=sc.fiji | a=register_virtual_stack_slices | label=register_virtual_stack_slices}}
| [[GPLv3]]
| {{Person|iarganda}}, {{Person|ctrueden}}
|-
| [https://imagej.net/registration_3d registration 3d]
| registration 3d plugin for Fiji.
| {{GitHub | org=fiji | repo=registration_3d}}
| {{Maven | g=sc.fiji | a=registration_3d | label=registration_3d}}
| [[GPLv3]]
| {{Person|StephanPreibisch}}, {{Person|ctrueden}}
|-
| [[Sholl|Sholl Analysis]]
| An ImageJ 1.x plugin that uses automated Sholl to perform neuronal morphometry directly from segmented images and traces from Simple Neurite Tracer
| {{GitHub | org=tferr | repo=ASA}}
| {{Maven | g=ca.mcgill | a=Sholl_Analysis | label=Sholl_Analysis}}
| [[GPLv3]]
| {{Person|tferr}}
|-
| [https://github.com/saalfeldlab/jitk-tps JavaITK thin plate spline]
| A java port of the ITK thin plate spline implementation.
| {{GitHub | org=saalfeldlab | repo=jitk-tps}}
| {{Maven | g=jitk | a=jitk-tps | label=jitk-tps}}
| [https://www.apache.org/licenses/LICENSE-2.0.txt Apache Software License, Version 2.0]
| {{Person|bogovicj}}, {{Person|axtimwalde}}
|-
| plugins/mpicbg_.jar
| 
| 
| {{Maven | g=mpicbg | a=mpicbg_ | label=mpicbg_}}
| [[GPLv3]]
| {{Person|dscho}}, {{Person|ctrueden}}, {{Person|hinerm}}
|-
| [http://www.openmicroscopy.org/site/products/bio-formats Bio-Formats Plugins for ImageJ]
| A collection of plugins for ImageJ, including the Bio-Formats Importer, Bio-Formats Exporter, Bio-Formats Macro Extensions, Data Browser and Stack Slicer.
| 
| {{Maven | g=ome | a=bio-formats_plugins | label=bio-formats_plugins}}
| [[GPLv2]]
| {{Person|curtis}}, {{Person|melissa}}
|-
| [[BigWarp|BigWarp plugin for Fiji]]
| A tool for manual pointwise deformable registration using bigdataviewer.
| {{GitHub | org=saalfeldlab | repo=bigwarp}}
| {{Maven | g=sc.fiji | a=bigwarp_fiji | label=bigwarp_fiji}}
| [[GPLv2]]
| {{Person|bogovicj}}, {{Person|axtimwalde}}
|-
| [https://github.com/saalfeldlab/trakem2-tps TrakEM2 thin plate splines]
| Thin plate splines in TrakEM2.
| {{GitHub | org=saalfeldlab | repo=trakem2-tps}}
| {{Maven | g=sc.fiji | a=trakem2_tps | label=trakem2_tps}}
| [[GPLv2]]
| {{Person|bogovicj}}, {{Person|axtimwalde}}
|-
| [https://github.com/bigdataviewer/bigdataviewer-core BigDataViewer Core]
| BigDataViewer core classes with minimal dependencies.
| {{GitHub | org=bigdataviewer | repo=bigdataviewer-core}}
| {{Maven | g=sc.fiji | a=bigdataviewer-core | label=bigdataviewer-core}}
| [[BSD-2]]
| {{Person|tpietzsch}}, {{Person|ctrueden}}
|-
| [http://github.com/bigdataviewer/bigdataviewer-vistools BigDataViewer Visualization Tools]
| Helpers to use BigDataViewer as quick visualization in other projects
| {{GitHub | org=bigdataviewer | repo=bigdataviewer-vistools}}
| {{Maven | g=sc.fiji | a=bigdataviewer-vistools | label=bigdataviewer-vistools}}
| [[BSD-2]]
| {{Person|tpietzsch}}, {{Person|ctrueden}}
|-
| [https://imagej.net/BigDataViewer BigDataViewer Fiji]
| Fiji plugins for starting BigDataViewer and exporting data.
| {{GitHub | org=bigdataviewer | repo=bigdataviewer_fiji}}
| {{Maven | g=sc.fiji | a=bigdataviewer_fiji | label=bigdataviewer_fiji}}
| [[GPLv3]]
| {{Person|tpietzsch}}, {{Person|ctrueden}}
|-
| [http://github.com/bigdataviewer/spimdata SPIM Data]
| representation of multi-angle, multi-channel (etc.) SPIM images and their registration
| {{GitHub | org=bigdataviewer | repo=spimdata}}
| {{Maven | g=sc.fiji | a=spim_data | label=spim_data}}
| [http://opensource.org/licenses/BSD-2-Clause BSD 2-Clause License]
| {{Person|tpietzsch}}, {{Person|StephanPreibisch}}
|-
| [https://imagej.net/TrakEM2 T2-NIT]
| T2-NIT component of TrakEM2 suite.
| {{GitHub | org=trakem2 | repo=TrakEM2}}
| {{Maven | g=sc.fiji | a=T2-NIT | label=T2-NIT}}
| [[GPLv3]]
| {{Person|acardona}}, {{Person|axtimwalde}}, {{Person|ctrueden}}
|-
| [https://imagej.net/TrakEM2 T2-TreelineGraph]
| T2-TreelineGraph component of TrakEM2 suite.
| {{GitHub | org=trakem2 | repo=TrakEM2}}
| {{Maven | g=sc.fiji | a=T2-TreelineGraph | label=T2-TreelineGraph}}
| [[GPLv3]]
| {{Person|acardona}}, {{Person|axtimwalde}}, {{Person|ctrueden}}
|-
| [https://imagej.net/TrakEM2 TrakEM2]
| TrakEM2 plugin for ImageJ.
| {{GitHub | org=trakem2 | repo=TrakEM2}}
| {{Maven | g=sc.fiji | a=TrakEM2_ | label=TrakEM2_}}
| [[GPLv3]]
| {{Person|acardona}}, {{Person|axtimwalde}}, {{Person|ctrueden}}
|-
| [https://imagej.net/TrakEM2 VectorString]
| VectorString component of TrakEM2 suite.
| {{GitHub | org=trakem2 | repo=TrakEM2}}
| {{Maven | g=sc.fiji | a=VectorString | label=VectorString}}
| [[GPLv3]]
| {{Person|acardona}}, {{Person|axtimwalde}}, {{Person|ctrueden}}
|-
| [https://imagej.net/TrakEM2 trakem2-transform]
| trakem2-transform component of TrakEM2 suite.
| {{GitHub | org=trakem2 | repo=TrakEM2}}
| {{Maven | g=sc.fiji | a=trakem2-transform | label=trakem2-transform}}
| [[GPLv3]]
| {{Person|acardona}}, {{Person|axtimwalde}}, {{Person|ctrueden}}
|-
| [http://www.joda.org/joda-time/ Joda-Time]
| Date and time library to replace JDK date handling
| {{GitHub | org=JodaOrg | repo=joda-time}}
| {{Maven | g=joda-time | a=joda-time | label=joda-time}}
| [[Apache]]
| {{Person|jodastephen}}, {{Person|broneill}}
|}
