<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = BigDataViewer Visualization Tools
| url = http://github.com/bigdataviewer/bigdataviewer-vistools
| source = {{GitHub | org=bigdataviewer | repo=bigdataviewer-vistools | tag=bigdataviewer-vistools-1.0.0-beta-5}}
| license = [[BSD-2]]
| release = {{Maven | g=sc.fiji | a=bigdataviewer-vistools | v=1.0.0-beta-5 | label=1.0.0-beta-5}}
| date = Wed May 17 16:40:49 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|tpietzsch}}
| leads = {{Person|tpietzsch}}
| developers = {{Person|tpietzsch}}
| debuggers = {{Person|tpietzsch}}
| reviewers = {{Person|tpietzsch}}
| support = {{Person|tpietzsch}}
| maintainers = {{Person|tpietzsch}}, {{Person|ctrueden}}
| contributors = {{Person|axtimwalde}}
}}
