<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = SciJava
| name = Native Library Loader
| url = https://github.com/scijava/native-lib-loader
| source = {{GitHub | org=scijava | repo=native-lib-loader | tag=native-lib-loader-2.1.5}}
| license = [[BSD-2]]
| release = {{Maven | g=org.scijava | a=native-lib-loader | v=2.1.5 | label=2.1.5}}
| date = Fri May 05 13:28:37 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|grislis}}, Richard van der Hoff
| leads = {{Person|ctrueden}}
| developers = {{Person|ctrueden}}
| debuggers = {{Person|ctrueden}}
| reviewers = {{Person|ctrueden}}
| support = {{Person|ctrueden}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|grislis}}, {{Person|dscho}}, {{Person|hinerm}}, {{Person|melissalinkert}}, {{Person|sbesson}}, Mark J H, Richard van der Hoff, Scott Cyphers, Yuriy Cherniavsky, {{Person|nitram509}}
}}
