<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Legacy ImgLib1
| url = https://imagej.net/ImgLib1_(deprecated)
| source = {{GitHub | org=fiji | repo=legacy-imglib1 | tag=legacy-imglib1-1.1.8}}
| license = [[BSD-2]], [[GPLv2]]
| release = {{Maven | g=sc.fiji | a=legacy-imglib1 | v=1.1.8 | label=1.1.8}}
| date = Wed May 24 15:30:44 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|StephanPreibisch}}, {{Person|axtimwalde}}
| leads = {{Person|StephanPreibisch}}, {{Person|axtimwalde}}
| maintainers = {{Person|StephanPreibisch}}, {{Person|axtimwalde}}, {{Person|ctrueden}}
| contributors = {{Person|acardona}}, {{Person|bdezonia}}, {{Person|funkey}}, {{Person|hinerm}}, Steffen Jaensch, {{Person|LeeKamentsky}}, {{Person|larrylindsey}}, {{Person|mhl}}, {{Person|nickp}}, {{Person|tpietzsch}}, {{Person|dscho}}
}}
