<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = SciJava
| name = SciJava Plugins: Commands
| url = https://imagej.net/SciJava Plugins: Commands
| source = {{GitHub | org=scijava | repo=scijava-plugins-commands | tag=scijava-plugins-commands-0.2.3}}
| license = [[BSD-2]]
| release = {{Maven | g=org.scijava | a=scijava-plugins-commands | v=0.2.3 | label=0.2.3}}
| date = Sun Apr 30 14:05:41 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|ctrueden}}
| leads = {{Person|ctrueden}}
| developers = {{Person|ctrueden}}
| debuggers = {{Person|ctrueden}}
| reviewers = {{Person|ctrueden}}
| support = {{Person|ctrueden}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}, {{Person|tnargsirrah}}
}}
