<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Graph Cut
| url = https://imagej.net/Graph_Cut
| source = {{GitHub | org=fiji | repo=Graph_Cut | tag=Graph_Cut-1.0.2}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=Graph_Cut | v=1.0.2 | label=1.0.2}}
| date = Sat Apr 29 22:44:45 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=yes | support=no}}
| founders = {{Person|funkey}}
| leads = {{Person|funkey}}
| reviewers = {{Person|funkey}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|acardona}}, {{Person|imagejan}}, {{Person|mhl}}, {{Person|panovr}}, {{Person|iarganda}}, {{Person|hinerm}}
}}
