<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = SPIM Data
| url = http://github.com/bigdataviewer/spimdata
| source = {{GitHub | org=bigdataviewer | repo=spimdata | tag=spim_data-2.2.0}}
| license = [http://opensource.org/licenses/BSD-2-Clause BSD 2-Clause License]
| release = {{Maven | g=sc.fiji | a=spim_data | v=2.2.0 | label=2.2.0}}
| date = Mon Aug 15 05:07:56 CDT 2016
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| developers = {{Person|tpietzsch}}, {{Person|StephanPreibisch}}
| contributors = {{Person|axtimwalde}}, {{Person|StephanPreibisch}}
| otherDevs = Tobias Pietzsch (architect), Stephan Preibisch (architect)
}}
