<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = FlowJ
| url = https://imagej.net/FlowJ
| source = {{GitHub | org=fiji | repo=FlowJ | tag=FlowJ_-1.29.3}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=FlowJ_ | v=1.29.3 | label=1.29.3}}
| date = Sat Apr 29 22:44:01 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|tinevez}}, Michael Abràmoff
| leads = {{Person|tinevez}}
| maintainers = {{Person|tinevez}}, {{Person|ctrueden}}
| contributors = Michael Abràmoff, {{Person|dscho}}, {{Person|hinerm}}
}}
