<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = RATS
| url = https://imagej.net/RATS
| source = {{GitHub | org=fiji | repo=RATS | tag=RATS_-2.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=RATS_ | v=2.0.1 | label=2.0.1}}
| date = Sat Apr 29 23:00:06 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|btupper}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|btupper}}, {{Person|dscho}}, {{Person|hinerm}}
}}
