<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = SciJava
| name = Swing Check Box Tree
| url = https://github.com/scijava/swing-checkbox-tree
| source = {{GitHub | org=scijava | repo=swing-checkbox-tree | tag=swing-checkbox-tree-1.0.2}}
| license = [[BSD-2]]
| release = {{Maven | g=org.scijava | a=swing-checkbox-tree | v=1.0.2 | label=1.0.2}}
| date = Fri May 05 10:16:49 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|ctrueden}}
| leads = {{Person|ctrueden}}
| developers = {{Person|ctrueden}}
| debuggers = {{Person|ctrueden}}
| reviewers = {{Person|ctrueden}}
| support = {{Person|ctrueden}}
| maintainers = {{Person|ctrueden}}
| contributors = John Zukowski
}}
