<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Thread Killer
| url = https://imagej.net/Thread_Killer
| source = {{GitHub | org=fiji | repo=Thread_Killer | tag=Thread_Killer-2.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=Thread_Killer | v=2.0.1 | label=2.0.1}}
| date = Sat Apr 29 23:10:25 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|dscho}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}
}}
