<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = Fiji Plugins
| url = https://imagej.net/Fiji_Plugins
| source = {{GitHub | org=fiji | repo=Fiji_Plugins | tag=Fiji_Plugins-3.1.1}}
| license = [[GPLv2]]
| release = {{Maven | g=sc.fiji | a=Fiji_Plugins | v=3.1.1 | label=3.1.1}}
| date = Sat Apr 29 22:43:05 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|acardona}}, {{Person|dscho}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|acardona}}, {{Person|dscho}}, {{Person|Gagbo}}, {{Person|iarganda}}, {{Person|imagejan}}, {{Person|haesleinhuepf}}, {{Person|hinerm}}, Francisco Jimenez-Hernandez, {{Person|StephanPreibisch}}, {{Person|tinevez}}
}}
