<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = SciJava
| name = Parsington: The SciJava Expression Parser
| url = https://github.com/scijava/parsington
| source = {{GitHub | org=scijava | repo=parsington | tag=parsington-1.0.1}}
| license = [[BSD-2]]
| release = {{Maven | g=org.scijava | a=parsington | v=1.0.1 | label=1.0.1}}
| date = Fri May 05 13:09:46 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|ctrueden}}
| leads = {{Person|ctrueden}}
| developers = {{Person|ctrueden}}
| debuggers = {{Person|ctrueden}}
| reviewers = {{Person|ctrueden}}
| support = {{Person|ctrueden}}
| maintainers = {{Person|ctrueden}}
| contributors = None
}}
