<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = SplineDeformationGenerator
| url = https://imagej.net/SplineDeformationGenerator
| source = {{GitHub | org=fiji | repo=SplineDeformationGenerator | tag=SplineDeformationGenerator_-2.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=SplineDeformationGenerator_ | v=2.0.1 | label=2.0.1}}
| date = Sat Apr 29 23:07:42 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|iarganda}}, {{Person|dscho}}
| leads = {{Person|iarganda}}
| debuggers = {{Person|iarganda}}
| reviewers = {{Person|iarganda}}
| support = {{Person|iarganda}}
| maintainers = {{Person|iarganda}}, {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}
}}
