<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = IsoData Classifier
| url = https://imagej.net/IsoData_Classifier
| source = {{GitHub | org=fiji | repo=IsoData_Classifier | tag=IsoData_Classifier-2.0.1}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=IsoData_Classifier | v=2.0.1 | label=2.0.1}}
| date = Sat Apr 29 22:50:56 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=no | support=no}}
| founders = {{Person|dscho}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|hinerm}}
}}
