<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = SciJava
| name = SciJava Scripting: Scala
| url = https://github.com/scijava/scripting-scala
| source = {{GitHub | org=scijava | repo=scripting-scala | tag=scripting-scala-0.2.1}}
| license = [[BSD-2]]
| release = {{Maven | g=org.scijava | a=scripting-scala | v=0.2.1 | label=0.2.1}}
| date = Sun Apr 30 14:16:56 CDT 2017
| devStatus = {{DevStatus | developer=yes | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=yes | reviewer=yes | support=yes}}
| founders = {{Person|dscho}}
| leads = {{Person|ctrueden}}
| developers = {{Person|ctrueden}}
| debuggers = {{Person|ctrueden}}
| reviewers = {{Person|ctrueden}}
| support = {{Person|ctrueden}}
| maintainers = {{Person|ctrueden}}
| contributors = {{Person|dscho}}, {{Person|keithschulze}}
}}
