<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = View5D
| url = https://imagej.net/View5D
| source = {{GitHub | org=fiji | repo=View5D | tag=View5D_-1.3.2}}
| license = [[GPLv2]]
| release = {{Maven | g=sc.fiji | a=View5D_ | v=1.3.2 | label=1.3.2}}
| date = Sat Apr 29 23:18:17 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=yes | support=yes}}
| founders = Rainer Heintzmann
| reviewers = {{Person|tinevez}}
| support = {{Person|tinevez}}
| maintainers = {{Person|tinevez}}, {{Person|ctrueden}}
| contributors = [[User:Heintzmann|Rainer Heintzmann]], {{Person|dscho}}, {{Person|hinerm}}
}}
