<noinclude>{{Autogenerated|template}}</noinclude>{{Component
| project = Fiji
| name = trakem2-transform
| url = https://imagej.net/TrakEM2
| source = {{GitHub | org=trakem2 | repo=TrakEM2 | tag=trakem2-transform-1.0.0}}
| license = [[GPLv3]]
| release = {{Maven | g=sc.fiji | a=trakem2-transform | v=1.0.0 | label=1.0.0}}
| date = Tue May 02 16:09:32 CDT 2017
| devStatus = {{DevStatus | developer=no | incubating=no | obsolete=no}}
| supportStatus = {{SupportStatus | debugger=no | reviewer=yes | support=yes}}
| founders = {{Person|acardona}}
| leads = {{Person|acardona}}, {{Person|axtimwalde}}
| reviewers = {{Person|axtimwalde}}
| support = {{Person|acardona}}
| maintainers = {{Person|axtimwalde}}, {{Person|ctrueden}}
| contributors = Sergio Jimenez-Celorrio, {{Person|vkaynig}}
}}
